version: "3.7"

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - type: volume
        source: postgres-cache
        target: /var/lib/postgresql/data
    logging:
      driver: none

  redis:
    image: redis
    volumes:
      - type: volume
        source: redis-cache
        target: /var/lib/redis/data
    logging:
      driver: none

  mailcatcher:
    build: ./.docker/mailcatcher
    ports:
      - target: 1080
        published: 1080
        protocol: tcp
        mode: host

  app:
    tty: true
    stdin_open: true
    build: .
    env_file:
      - docker-app.env
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
        mode: host
    volumes:
      - .:/app:delegated
      - type: volume
        source: gem-cache
        target: /usr/local/bundle
    depends_on:
      - postgres
      - redis

  jobs:
    build: .
    command: ["./docker-jobs-init.sh"]
    env_file:
      - docker-app.env
    volumes:
      - .:/app:delegated
    depends_on:
      - postgres
      - redis
      - app

volumes:
  postgres-cache:
  redis-cache:
  gem-cache:
