version: "3.7"

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - type: volume
        source: postgres-cache
        target: /var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - target: 6379
        published: 6379
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: redis-cache
        target: /var/lib/redis/data

  box:
    image: busybox
    volumes:
      - /box

  app:
    tty: true
    stdin_open: true
    build: .
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      REDIS_SERVER: redis://redis:6379/0
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
        mode: host
    volumes:
      - .:/app
      - type: volume
        source: gem-cache
        target: /usr/local/bundle
    depends_on:
      - db
      - redis

  jobs:
    build: .
    command: ["./jobs-init.sh"]
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      REDIS_SERVER: redis://redis:6379/0
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
      - app

volumes:
  postgres-cache:
  redis-cache:
  gem-cache:
  box:
