name: Pull Request

on:
  pull_request:
    branches:
    - master

env:
  RAILS_ENV: test

jobs:
  rspec:
    name: rspec
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:alpine
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Load bundler cache
      id: gem-cache
      uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}

    - name: Set up ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x

    - name: Set up dependencies
      run: |
        gem install bundler -v 2.1.4 --no-document
        bundle install --jobs=4 --retry 3

    - name: Set up database
      env:
        POSTGRES_HOST: localhost
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
      run: |
        bin/rails db:create
        bin/rails db:schema:load

    - name: Test
      env:
        POSTGRES_HOST: localhost
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
      run: bin/rspec --fail-fast --format progress

  rubocop:
    name: rubocop
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - run: |
        git fetch --no-tags --prune --depth=1 \
          origin +refs/heads/*:refs/remotes/origin/*

    - name: Load bundler cache
      id: gem-cache
      uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}

    - name: Set up ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x

    - name: Set up dependencies
      run: |
        gem install bundler -v 2.1.4 --no-document
        bundle install --jobs=4 --retry 3

    - name: Lint
      run: >-
        bin/rubocop --force-exclusion
          $(git diff --name-status origin/${{ github.base_ref }} |
          grep -v -e '^[DUR]' | sed "s/^[a-zA-Z]*[^a-zA-Z0-9\.]*//")
